const { fakerEN: faker } = require('@faker-js/faker')
const CategoryExam = require('../models/category_exam')

const sampleNames = [
  'Basic Exam',
  'Practical Exercise',
  'Final Exam',
  'Midterm Exam',
  'Essay Exam'
]

const sampleDescriptions = [
  'A basic exam covering the knowledge learned in the curriculum.',
  'A practical exercise to apply knowledge into practice.',
  'A final exam evaluating all the knowledge learned in a semester.',
  'A midterm exam assessing the learned knowledge after a certain period of time.',
  'An essay exam requiring students to present opinions, viewpoints, or solve problems.'
]
/**
 * Generates a list of category exams.
 *
 * This function creates an array of category exams using sample names and descriptions.
 * Each category exam includes a name, description, created date, and updated date.
 *
 * @author Canh
 * @returns {Promise<Array<Object>>} A promise that resolves to an array of category exam objects.
 */
const generateCategoryExam = async () => {
  const categoryExams = []

  for (let i = 0; i < sampleNames.length; i++) {
    const name = sampleNames[i]
    const description = sampleDescriptions[i]

    categoryExams.push({
      name,
      description,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent()
    })
  }

  return categoryExams
}

/**
 * Seed the category exams table with sample data.
 *
 * This function seeds the category exams table with sample data generated by the generateCategoryExam function.
 * It first checks if the table is empty, and if so, it populates the table with the generated data.
 *
 * @author Canh
 * @returns {Promise<void>} A promise that resolves when the seeding is complete.
 */
const seedCategoryExams = async () => {
  // Generate sample category exams data
  const categoryExams = await generateCategoryExam()
  try {
    // Check if the category exams table is empty
    const count = await CategoryExam.count()
    if (count === 0) {
      // If the table is empty, bulk create the sample data
      await CategoryExam.bulkCreate(categoryExams, { validate: true })
    } else {
      // If the table is not empty, log a message
      console.log('CategoryExam table is not empty.')
    }
  } catch (error) {
    // Log any errors that occur during the seeding process
    console.log(`Failed to seed CategoryExam data: ${error}`)
  }
}

module.exports = seedCategoryExams
