const { fakerEN: faker } = require('@faker-js/faker')
const CategoryCourse = require('../models/category_course')

const sampleNames = ['WACA', 'FaceFarm']

const sampleDescriptions = [
  'Phần mềm kế toán Hợp tác xã nông nghiệp WACA',
  'Nhật ký sản xuất FaceFarm'
]
/**
 * Generates a list of category courses.
 *
 * This function creates an array of category courses using sample names and descriptions.
 * Each category course includes a name, description, created date, and updated date.
 *
 * @author Canh
 * @returns {Promise<Array<Object>>} A promise that resolves to an array of category course objects.
 */
const generateCategoryCourse = async () => {
  const categoryCourses = []

  for (let i = 0; i < sampleNames.length; i++) {
    const name = sampleNames[i]
    const description = sampleDescriptions[i]

    categoryCourses.push({
      name,
      description,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent()
    })
  }

  return categoryCourses
}
/**
 * Seed the category courses table with sample data.
 *
 * This function seeds the category courses table with sample data generated by the generateCategoryCourse function.
 * It first checks if the table is empty, and if so, it populates the table with the generated data.
 *
 * @author Canh
 * @returns {Promise<void>} A promise that resolves when the seeding is complete.
 */
const seedCategoryCourses = async () => {
  // Generate sample category courses data
  const categoryCourses = await generateCategoryCourse()

  try {
    // Check if the category courses table is empty
    const count = await CategoryCourse.count()
    if (count === 0) {
      // If the table is empty, bulk create the sample data
      await CategoryCourse.bulkCreate(categoryCourses, { validate: true })
    } else {
      // If the table is not empty, log a message
      console.log('categoryCourses table is not empty.')
    }
  } catch (error) {
    // Log any errors that occur during the seeding process
    console.log(`Failed to seed categoryCourses data: ${error}`)
  }
}

module.exports = seedCategoryCourses
