const { fakerEN: faker } = require('@faker-js/faker')
const Course = require('../models/course')
const CategoryLession = require('../models/category_lession')

const sampleNames = [
  'Đăng ký và Kích hoạt Tài khoản', 'Đăng nhập và Quản lý Tài khoản', 'Tương tác với Phần mềm',
  'Khai báo và Đăng ký Thông tin', 'Quản lý Đối tượng và Góp vốn', 'Xử lý Giao dịch Tài chính',
  'Khai báo Hàng hóa và Vật tư', 'Quản lý Tồn kho Thành phẩm', 'Báo cáo và Phân tích Tồn kho',
  'Quản lý Tài sản Cố định', 'Quản lý Chi phí Trả trước', 'Xử lý Chi phí Sản xuất',
  'Quản lý Phải thu và Phải trả', 'Quản lý Lợi nhuận và Quỹ', 'Lập và Trình bày Báo cáo Tài chính',
  'Tổng quan về FaceFarm', 'Thiết lập tài khoản FaceFarm', 'Hướng dẫn cơ bản sử dụng FaceFarm',
  'Nhập liệu và quản lý nhật ký', 'Theo dõi và cập nhật tiến độ', 'Phân tích dữ liệu nhật ký',
  'Quản lý danh mục nông dược', 'Quản lý danh mục phân bón', 'Tính toán và dự trù sử dụng',
  'Thiết lập thông tin nhân công', 'Quản lý công việc sản xuất', 'Tối ưu hóa quy trình sản xuất',
  'Ứng dụng ghi chép nhanh', 'Quản lý và phân phối sản phẩm', 'Tích hợp và mở rộng'
]
/**
 * Generates a list of category lessons for each course.
 *
 * This function creates an array of category lessons for each course in the database.
 * Each course will have a fixed number of lessons, and each lesson will include details such as
 * course ID, name, order, check-up date, creation date, and update date.
 *
 * @author Canh
 * @returns {Promise<Array<Object>>} A promise that resolves to an array of category lesson objects.
 */
const generateCategoryLession = async () => {
  const categoryLessions = []
  const courses = await Course.findAll()
  let nameIndex = 0

  for (let i = 0; i < courses.length; i++) {
    const course = courses[i]
    const courseId = course.id
    const numLessons = 3
    let order = 1
    const checkUpDate = new Date()

    for (let j = 0; j < numLessons; j++) {
      const categoryLessonName = sampleNames[nameIndex % sampleNames.length]
      nameIndex++

      categoryLessions.push({
        courseId,
        name: categoryLessonName,
        order,
        checkUpDate,
        createAt: faker.date.past(),
        updatedAt: faker.date.recent()
      })
      order += 1
    }
  }
  return categoryLessions
}

/**
 * Seed the category lessons table with sample data.
 *
 * This function seeds the category lessons table with sample data generated by the generateCategoryLession function.
 * It first checks if the table is empty, and if so, it populates the table with the generated data.
 *
 * @author Canh
 * @returns {Promise<void>} A promise that resolves when the seeding is complete.
 */
const seedCategoryLession = async () => {
  try {
    // Check if the category lessons table is empty
    const count = await CategoryLession.count()
    if (count === 0) {
      // If the table is empty, generate sample category lessons data
      const categorylessions = await generateCategoryLession()
      // Bulk create the sample data
      await CategoryLession.bulkCreate(categorylessions, { validate: true })
    } else {
      // If the table is not empty, log a message
      console.log('CategoryLession table is not empty.')
    }
  } catch (error) {
    // Log any errors that occur during the seeding process
    console.log(`Failed to seed CategoryLession data: ${error}`)
  }
}

module.exports = seedCategoryLession
