const { fakerEN: faker } = require('@faker-js/faker')
const Enrollment = require('../models/enrollments')
const Lession = require('../models/lession')
const CourseProgress = require('../models/course_progress')
/**
 * Generate a random enrollment ID.
 *
 * This function retrieves all enrollments from the database, extracts their IDs,
 * and returns a randomly selected enrollment ID.
 *
 * @author Canh
 * @returns {Promise<number>} A promise that resolves to a random enrollment ID.
 */
const generateEnrollmentId = async () => {
  const enrollments = await Enrollment.findAll()
  const enrollmentIds = enrollments.map(enrollment => enrollment.id)
  const randomIndex = Math.floor(Math.random() * enrollmentIds.length)
  const randomEnrollmentId = enrollmentIds[randomIndex]
  return randomEnrollmentId
}
/**
 * Generate a random lesson ID.
 *
 * This function retrieves all lessons from the database, extracts their IDs,
 * and returns a randomly selected lesson ID.
 *
 * @author Canh
 * @returns {Promise<number>} A promise that resolves to a random lesson ID.
 */
const generateLessionId = async () => {
  const lessions = await Lession.findAll()
  const lessionIds = lessions.map(lession => lession.id)
  const randomIndex = Math.floor(Math.random() * lessionIds.length)
  const randomLessionId = lessionIds[randomIndex]
  return randomLessionId
}
/**
 * Generate sample course progress data.
 *
 * This function generates an array of sample course progress data, ensuring that
 * each enrollment-lesson pair is unique. Each course progress entry includes
 * enrollment ID, lesson ID, completion date, creation date, and update date.
 *
 * @author Canh
 * @returns {Promise<Array<Object>>} A promise that resolves to an array of course progress objects.
 */
const generateCourseProgress = async () => {
  const usedPairs = new Set()
  const courseProgress = []

  while (courseProgress.length < 10) {
    const enrollmentId = await generateEnrollmentId()
    const lessionId = await generateLessionId()
    const pair = `${enrollmentId}-${lessionId}`

    if (!usedPairs.has(pair)) {
      courseProgress.push({
        enrollmentId,
        lessionId,
        completeation_at: faker.date.recent(),
        createdAt: faker.date.past(),
        updatedAt: faker.date.recent()
      })
    }
  }
  return courseProgress
}

/**
 * Seed the course progress table with sample data.
 *
 * This function seeds the course progress table with sample data generated by the generateCourseProgress function.
 * It first checks if the table is empty, and if so, it populates the table with the generated data.
 *
 * @author Canh
 * @returns {Promise<void>} A promise that resolves when the seeding is complete.
 */
const seedCourseProgress = async () => {
  try {
    // Check if the course progress table is empty
    const count = await CourseProgress.count()
    if (count === 0) {
      // If the table is empty, generate sample course progress data
      const courseProgress = await generateCourseProgress()
      // Bulk create the sample data
      await CourseProgress.bulkCreate(courseProgress, { validate: true })
    } else {
      // If the table is not empty, log a message
      console.log('CourseProgress table is not empty.')
    }
  } catch (error) {
    // Log any errors that occur during the seeding process
    console.log(`Failed to seed CourseProgress data: ${error}`)
  }
}

module.exports = seedCourseProgress
