/* eslint-disable camelcase */
const { fakerEN: faker } = require('@faker-js/faker')
const Enrollment = require('../models/enrollments')
const User = require('../models/user')
const Course = require('../models/course')
/**
 * Generate a random user ID.
 *
 * This function retrieves all users from the database, extracts their IDs,
 * and returns a randomly selected user ID.
 *
 * @author Canh
 * @returns {Promise<number>} A promise that resolves to a random user ID.
 */
const generateUserId = async () => {
  const users = await User.findAll()
  const userIds = users.map(user => user.id)
  const randomIndex = Math.floor(Math.random() * userIds.length)
  const randomUserId = userIds[randomIndex]
  return randomUserId
}
/**
 * Generate a random course ID.
 *
 * This function retrieves all courses from the database, extracts their IDs,
 * and returns a randomly selected course ID.
 *
 * @author Canh
 * @returns {Promise<number>} A promise that resolves to a random course ID.
 */
const generateCourseId = async () => {
  const courses = await Course.findAll()
  const courseIds = courses.map(course => course.id)
  const randomIndex = Math.floor(Math.random() * courseIds.length)
  const randomCourseId = courseIds[randomIndex]
  return randomCourseId
}

/**
 * Generate sample enrollment data.
 *
 * This function generates an array of sample enrollment data, ensuring that
 * each user-course pair is unique. Each enrollment entry includes user ID,
 * course ID, enrollment date, creation date, update date, status, progress,
 * and completion date.
 *
 * @author Canh
 * @returns {Promise<Array<Object>>} A promise that resolves to an array of enrollment objects.
 */
const generateEnrollment = async () => {
  const usedPairs = new Set()
  const enrollments = []

  while (enrollments.length < 10) {
    const userId = await generateUserId()
    const courseId = await generateCourseId()
    const pair = `${userId}-${courseId}`

    if (!usedPairs.has(pair)) {
      usedPairs.add(pair)
      const enrollment_date = faker.date.past()
      enrollments.push({
        userId,
        courseId,
        enrollment_date,
        createdAt: faker.date.past(),
        updatedAt: faker.date.recent(),
        status: false,
        progress: 0,
        completedDate: null
      })
    }
  }
  return enrollments
}
/**
 * Seed the enrollment table with sample data.
 *
 * This function seeds the enrollment table with sample data generated by the generateEnrollment function.
 * It first checks if the table is empty, and if so, it populates the table with the generated data.
 *
 * @author Canh
 * @returns {Promise<void>} A promise that resolves when the seeding is complete.
 */
const seedEnrollment = async () => {
  try {
    const count = await Enrollment.count()
    if (count === 0) {
      const enrollments = await generateEnrollment()
      await Enrollment.bulkCreate(enrollments, { validate: true })
    } else {
      console.log('Enrollment table is not empty.')
    }
  } catch (error) {
    console.log(`Failed to seed Enrollment data: ${error}`)
  }
}

module.exports = seedEnrollment
