const { fakerEN: faker } = require('@faker-js/faker')
const Notification = require('../models/notification')
/**
 * Generate sample notifications data.
 *
 * This function generates an array of sample notifications data. Each notification entry includes
 * a title, message, URL, creation date, and update date.
 *
 * @author Canh
 * @returns {Promise<Array<Object>>} A promise that resolves to an array of notification objects.
 */
const generateNotifications = async () => {
  const urls = ['/myCourses', '/learning/1?id=1']

  return await Promise.all(Array.from({ length: 10 }, async () => ({
    title: faker.lorem.words(2)
      .split(' ')
      .map(word => word.charAt(0).toLocaleUpperCase() + word.slice(1))
      .join(' '),
    message: faker.lorem.sentence(),
    url: urls[Math.floor(Math.random() * urls.length)],
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent()
  })))
}
/**
 * Seed the notifications table with sample data.
 *
 * This function seeds the notifications table with sample data generated by the generateNotifications function.
 * It first checks if the table is empty, and if so, it populates the table with the generated data.
 *
 * @author Canh
 * @returns {Promise<void>} A promise that resolves when the seeding is complete.
 */
const seedNotifications = async () => {
  try {
    // Check if the notifications table is empty
    const count = await Notification.count()
    if (count === 0) {
      // If the table is empty, generate sample notifications data
      const notifications = await generateNotifications()
      // Bulk create the sample data
      await Notification.bulkCreate(notifications, { validate: true })
    } else {
      // If the table is not empty, log a message
      console.log('Notifications table is not empty.')
    }
  } catch (error) {
    // Log any errors that occur during the seeding process
    console.log(`Failed to seed Notifications data: ${error}`)
  }
}

module.exports = seedNotifications
