/* eslint-disable camelcase */
const { fakerEN: faker } = require('@faker-js/faker')
const NotificationRecipient = require('../models/notification_recipient')
const User = require('../models/user')
const Notification = require('../models/notification')
/**
 * Generate a random user ID.
 *
 * This function retrieves all users from the database, extracts their IDs,
 * and returns a randomly selected user ID.
 *
 * @author Canh
 * @returns {Promise<number>} A promise that resolves to a random user ID.
 */
const generateUserId = async () => {
  const users = await User.findAll()
  const userIds = users.map(user => user.id)
  const randomIndex = Math.floor(Math.random() * userIds.length)
  const randomUserId = userIds[randomIndex]
  return randomUserId
}

/**
 * Generate a random notification ID.
 *
 * This function retrieves all notifications from the database, extracts their IDs,
 * and returns a randomly selected notification ID.
 *
 * @author Canh
 * @returns {Promise<number>} A promise that resolves to a random notification ID.
 */
const generateNotificationId = async () => {
  const notifications = await Notification.findAll()
  const notiIds = notifications.map(noti => noti.id)
  const randomIndex = Math.floor(Math.random() * notiIds.length)
  const randomNotiId = notiIds[randomIndex]
  return randomNotiId
}
/**
 * Generate sample notification recipient data.
 *
 * This function generates an array of sample notification recipient data, ensuring that
 * each user-notification pair is unique. Each notification recipient entry includes user ID,
 * notification ID, status, creation date, and update date.
 *
 * @author Canh
 * @returns {Promise<Array<Object>>} A promise that resolves to an array of notification recipient objects.
 */
const generateNotificationRecipient = async () => {
  const usedPairs = new Set()
  const notifications = []

  while (notifications.length < 10) {
    const userId = await generateUserId()
    const notificationId = await generateNotificationId()
    const pair = `${userId}-${notificationId}`

    if (!usedPairs.has(pair)) {
      usedPairs.add(pair)
      notifications.push({
        userId,
        notificationId,
        status: false,
        createdAt: faker.date.past(),
        updatedAt: faker.date.recent()
      })
    }
  }
  return notifications
}

/**
 * Seed the notification recipients table with sample data.
 *
 * This function seeds the notification recipients table with sample data generated by the generateNotificationRecipient function.
 * It first checks if the table is empty, and if so, it populates the table with the generated data.
 *
 * @author Canh
 * @returns {Promise<void>} A promise that resolves when the seeding is complete.
 */
const seedNotificationRecipient = async () => {
  try {
    // Check if the notification recipients table is empty
    const count = await NotificationRecipient.count()
    if (count === 0) {
      // If the table is empty, generate sample notification recipients data
      const notification_recipients = await generateNotificationRecipient()
      // Bulk create the sample data
      await NotificationRecipient.bulkCreate(notification_recipients, { validate: true })
    } else {
      // If the table is not empty, log a message
      console.log('NotificationRecipient table is not empty.')
    }
  } catch (error) {
    // Log any errors that occur during the seeding process
    console.log(`Failed to seed NotificationRecipient data: ${error}`)
  }
}

module.exports = seedNotificationRecipient
