const { fakerEN: faker } = require('@faker-js/faker')
const Question = require('../models/question')

const instructionExamples = [
  'Choose the correct answer:',
  'Select the appropriate option:',
  'Pick the best answer:',
  'Indicate the correct choice:',
  'Choose the most suitable option:',
  'Select the right response:'
]
const questionExamples = [
  {
    content: 'Ngôn ngữ lập trình nào sau đây thường được sử dụng để phát triển ứng dụng web front-end?',
    type: 'MULTIPLE_CHOICE',
    a: 'Java',
    b: 'Python',
    c: 'JavaScript',
    d: 'C++',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a::b::c',
    explanation: 'JavaScript là ngôn ngữ lập trình chính được sử dụng để phát triển giao diện người dùng của website, trong khi Java và Python thường dùng cho backend, C++ cho các ứng dụng hệ thống.'
  },
  {
    content: 'Đâu là một hệ quản trị cơ sở dữ liệu quan hệ?',
    type: 'SINGLE_CHOICE',
    a: 'MySQL',
    b: 'MongoDB',
    c: 'Redis',
    d: 'Cassandra',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a',
    explanation: 'MySQL là một hệ quản trị cơ sở dữ liệu quan hệ, trong khi MongoDB, Redis, và Cassandra là các hệ quản trị cơ sở dữ liệu NoSQL.'
  },
  {
    content: "Thuật ngữ 'API' thường được viết tắt cho điều gì trong IT?",
    type: 'SINGLE_CHOICE',
    a: 'Advanced Programming Interface',
    b: 'Application Programming Interface',
    c: 'Application Process Integration',
    d: 'Advanced Process Integration',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'b',
    explanation: 'API là viết tắt của Application Programming Interface, một tập hợp các định nghĩa và giao thức để xây dựng và tích hợp phần mềm ứng dụng.'
  },
  {
    content: 'Trong mô hình OSI, tầng nào chịu trách nhiệm định tuyến dữ liệu giữa các mạng?',
    type: 'SINGLE_CHOICE',
    a: 'Tầng Vật lý (Physical Layer)',
    b: 'Tầng Mạng (Network Layer)',
    c: 'Tầng Vận chuyển (Transport Layer)',
    d: 'Tầng Ứng dụng (Application Layer)',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'b',
    explanation: 'Tầng Mạng (Network Layer) trong mô hình OSI chịu trách nhiệm định tuyến dữ liệu giữa các mạng khác nhau.'
  },
  {
    content: 'Ngôn ngữ nào thường được sử dụng cho các ứng dụng khoa học dữ liệu và học máy?',
    type: 'SINGLE_CHOICE',
    a: 'PHP',
    b: 'Ruby',
    c: 'Python',
    d: 'Swift',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Python là ngôn ngữ phổ biến nhất trong khoa học dữ liệu và học máy nhờ thư viện phong phú và cú pháp dễ đọc.'
  },
  {
    content: "Khái niệm 'RESTful' thường được liên kết với loại kiến trúc nào?",
    type: 'SINGLE_CHOICE',
    a: 'Kiến trúc hướng sự kiện',
    b: 'Kiến trúc Microservices',
    c: 'Kiến trúc Dịch vụ Web',
    d: 'Kiến trúc Máy chủ - Client',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'RESTful thường được liên kết với kiến trúc Dịch vụ Web (Web Services) để thiết kế các API.'
  },
  {
    content: 'Trong hệ điều hành Linux, lệnh nào sau đây được sử dụng để thay đổi quyền truy cập của tệp?',
    type: 'SINGLE_CHOICE',
    a: 'chmod',
    b: 'chown',
    c: 'chgrp',
    d: 'sudo',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a',
    explanation: 'Lệnh chmod được sử dụng để thay đổi quyền truy cập (đọc, viết, thực thi) của các tập tin và thư mục trên Linux.'
  },
  {
    content: 'Đâu là một framework phổ biến cho phát triển ứng dụng web bằng Python?',
    type: 'SINGLE_CHOICE',
    a: 'React',
    b: 'Angular',
    c: 'Django',
    d: 'Vue.js',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Django là một framework web phổ biến cho Python, trong khi React, Angular, và Vue.js thường được sử dụng cho front-end.'
  },
  {
    content: 'Công cụ nào sau đây thường được dùng để container hóa ứng dụng?',
    type: 'SINGLE_CHOICE',
    a: 'npm',
    b: 'pip',
    c: 'Docker',
    d: 'Maven',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Docker là một nền tảng phổ biến để xây dựng, triển khai và quản lý các ứng dụng container.'
  },
  {
    content: "Thuật ngữ 'Cloud Computing' dùng để chỉ điều gì?",
    type: 'SINGLE_CHOICE',
    a: 'Việc phát triển phần mềm trên các thiết bị di động',
    b: 'Việc sử dụng các máy tính cá nhân để lưu trữ dữ liệu',
    c: 'Việc cung cấp tài nguyên điện toán qua internet',
    d: 'Việc tạo các mạng cục bộ',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Cloud Computing đề cập đến việc cung cấp các dịch vụ điện toán như máy chủ, lưu trữ, cơ sở dữ liệu qua Internet.'
  },
  {
    content: 'Công nghệ nào sau đây thường được sử dụng để xây dựng các trang web động?',
    type: 'SINGLE_CHOICE',
    a: 'HTML',
    b: 'CSS',
    c: 'JavaScript',
    d: 'XML',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'JavaScript được sử dụng rộng rãi để tạo các trang web động, tương tác và thực hiện các chức năng phía client-side.'
  },
  {
    content: "Trong lập trình hướng đối tượng, 'kế thừa' có nghĩa là gì?",
    type: 'SINGLE_CHOICE',
    a: 'Một đối tượng có thể chứa nhiều đối tượng khác',
    b: 'Một đối tượng có thể tạo ra một bản sao mới của chính nó',
    c: 'Một đối tượng có thể sử dụng lại các thuộc tính và phương thức của đối tượng khác',
    d: 'Một đối tượng có thể thay đổi trạng thái của đối tượng khác',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Kế thừa cho phép một lớp (đối tượng) có thể sử dụng các thuộc tính và phương thức của một lớp (đối tượng) khác, tạo ra mối quan hệ phân cấp.'
  },
  {
    content: "Trong mạng máy tính, 'IP address' là gì?",
    type: 'SINGLE_CHOICE',
    a: 'Địa chỉ vật lý của thiết bị',
    b: 'Địa chỉ logic của thiết bị trên mạng',
    c: 'Tên của thiết bị',
    d: 'Mật khẩu của thiết bị',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'b',
    explanation: 'Địa chỉ IP (Internet Protocol address) là một địa chỉ logic để xác định thiết bị trên mạng.'
  },
  {
    content: 'Công nghệ nào thường được sử dụng để quản lý và phân tích dữ liệu lớn (Big Data)?',
    type: 'SINGLE_CHOICE',
    a: 'Microsoft Access',
    b: 'Excel',
    c: 'Hadoop',
    d: 'MySQL',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Hadoop là một framework phổ biến để xử lý và phân tích dữ liệu lớn.'
  },
  {
    content: 'Trong JavaScript, phương thức nào được sử dụng để thêm phần tử vào cuối mảng?',
    type: 'SINGLE_CHOICE',
    a: 'push()',
    b: 'pop()',
    c: 'shift()',
    d: 'unshift()',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a',
    explanation: 'Phương thức push() được sử dụng để thêm phần tử mới vào cuối mảng trong JavaScript.'
  },
  {
    content: 'Giao thức nào được sử dụng để gửi email?',
    type: 'SINGLE_CHOICE',
    a: 'HTTP',
    b: 'SMTP',
    c: 'FTP',
    d: 'IMAP',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'b',
    explanation: 'SMTP (Simple Mail Transfer Protocol) được sử dụng để gửi email.'
  },
  {
    content: 'Công cụ nào sau đây được sử dụng để quản lý các package trong Node.js?',
    type: 'SINGLE_CHOICE',
    a: 'npm',
    b: 'pip',
    c: 'yarn',
    d: 'composer',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a',
    explanation: 'npm (Node Package Manager) là công cụ quản lý package mặc định của Node.js.'
  },
  {
    content: 'Đâu là một hệ điều hành mã nguồn mở phổ biến?',
    type: 'SINGLE_CHOICE',
    a: 'Windows',
    b: 'Linux',
    c: 'macOS',
    d: 'iOS',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'b',
    explanation: 'Linux là một hệ điều hành mã nguồn mở phổ biến được sử dụng rộng rãi.'
  },
  {
    content: 'Công cụ nào được sử dụng để kiểm tra và phát hiện lỗi của các trang web?',
    type: 'SINGLE_CHOICE',
    a: 'Postman',
    b: 'Jenkins',
    c: 'Selenium',
    d: 'Docker',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Selenium là công cụ tự động hóa phổ biến để kiểm tra và phát hiện lỗi trên các trang web.'
  },
  {
    content: 'Trong JavaScript, từ khóa nào được sử dụng để khai báo một biến không thể thay đổi?',
    type: 'SINGLE_CHOICE',
    a: 'var',
    b: 'let',
    c: 'const',
    d: 'static',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Từ khóa const trong JavaScript được sử dụng để khai báo biến không thể thay đổi giá trị.'
  },
  {
    content: 'Đâu là công cụ phổ biến để quản lý phiên bản mã nguồn?',
    type: 'SINGLE_CHOICE',
    a: 'Git',
    b: 'Node.js',
    c: 'PHP',
    d: 'MySQL',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a',
    explanation: 'Git là công cụ kiểm soát phiên bản được sử dụng rộng rãi trong phát triển phần mềm.'
  },
  {
    content: 'JavaScript thuộc kiểu ngôn ngữ nào?',
    type: 'SINGLE_CHOICE',
    a: 'Ngôn ngữ lập trình hướng đối tượng',
    b: 'Ngôn ngữ kịch bản',
    c: 'Ngôn ngữ lập trình biên dịch',
    d: 'Ngôn ngữ lập trình chức năng',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'b',
    explanation: 'JavaScript là một ngôn ngữ kịch bản chủ yếu chạy trên trình duyệt web.'
  },
  {
    content: 'Câu lệnh nào trong SQL dùng để xóa dữ liệu từ bảng?',
    type: 'SINGLE_CHOICE',
    a: 'DELETE',
    b: 'DROP',
    c: 'REMOVE',
    d: 'CLEAR',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a',
    explanation: 'Câu lệnh DELETE được sử dụng để xóa dữ liệu từ một bảng trong cơ sở dữ liệu SQL.'
  },
  {
    content: 'Lệnh nào dùng để kiểm tra trạng thái của Git repository?',
    type: 'SINGLE_CHOICE',
    a: 'git log',
    b: 'git branch',
    c: 'git status',
    d: 'git commit',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Lệnh `git status` hiển thị thông tin về trạng thái hiện tại của Git repository.'
  },
  {
    content: 'Trong HTML, thuộc tính nào dùng để đặt đường dẫn của hình ảnh?',
    type: 'SINGLE_CHOICE',
    a: 'alt',
    b: 'href',
    c: 'src',
    d: 'path',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Thuộc tính `src` trong HTML dùng để đặt đường dẫn của hình ảnh.'
  },
  {
    content: 'Framework nào sau đây được sử dụng để xây dựng giao diện người dùng trên web?',
    type: 'SINGLE_CHOICE',
    a: 'Django',
    b: 'React',
    c: 'Flask',
    d: 'Laravel',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'b',
    explanation: 'React là một thư viện JavaScript được sử dụng để xây dựng giao diện người dùng.'
  },
  {
    content: 'Phương thức nào dùng để chuyển một chuỗi thành chữ in hoa trong JavaScript?',
    type: 'SINGLE_CHOICE',
    a: 'toUpperCase()',
    b: 'toLowerCase()',
    c: 'toString()',
    d: 'charAt()',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a',
    explanation: 'Phương thức `toUpperCase()` trong JavaScript được sử dụng để chuyển đổi chuỗi thành chữ in hoa.'
  },
  {
    content: 'Trong CSS, thuộc tính nào dùng để thay đổi màu chữ?',
    type: 'SINGLE_CHOICE',
    a: 'color',
    b: 'background-color',
    c: 'font-color',
    d: 'text-color',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a',
    explanation: 'Thuộc tính `color` trong CSS dùng để thay đổi màu chữ.'
  },
  {
    content: 'Phương thức nào trong JavaScript dùng để kiểm tra xem một chuỗi có bắt đầu bằng một chuỗi con cụ thể không?',
    type: 'SINGLE_CHOICE',
    a: 'includes()',
    b: 'startsWith()',
    c: 'endsWith()',
    d: 'indexOf()',
    answer: 'b',
    explanation: '`startsWith()` kiểm tra chuỗi có bắt đầu bằng chuỗi con được chỉ định không.'
  },
  {
    content: 'Lệnh nào dùng để tạo một bảng mới trong SQL?',
    type: 'SINGLE_CHOICE',
    a: 'CREATE TABLE',
    b: 'INSERT INTO',
    c: 'ALTER TABLE',
    d: 'NEW TABLE',
    answer: 'a',
    explanation: '`CREATE TABLE` được dùng để tạo bảng mới trong cơ sở dữ liệu.'
  },
  {
    content: 'Trong HTML, thẻ nào dùng để tạo danh sách có thứ tự?',
    type: 'SINGLE_CHOICE',
    a: '<ul>',
    b: '<ol>',
    c: '<li>',
    d: '<dl>',
    answer: 'b',
    explanation: 'Thẻ `<ol>` được dùng để tạo danh sách có thứ tự.'
  },
  {
    content: 'Trong React, hook nào được sử dụng để quản lý trạng thái của component?',
    type: 'SINGLE_CHOICE',
    a: 'useEffect',
    b: 'useState',
    c: 'useContext',
    d: 'useReducer',
    answer: 'b',
    explanation: '`useState` là hook dùng để quản lý trạng thái trong React function component.'
  },
  {
    content: 'Hàm nào trong Python dùng để sắp xếp một danh sách?',
    type: 'SINGLE_CHOICE',
    a: 'sort()',
    b: 'sorted()',
    c: 'arrange()',
    d: 'order()',
    answer: 'b',
    explanation: '`sorted()` là hàm tích hợp trong Python dùng để sắp xếp danh sách.'
  },
  {
    content: 'Thuộc tính nào của CSS dùng để căn giữa nội dung theo chiều ngang?',
    type: 'SINGLE_CHOICE',
    a: 'text-align',
    b: 'justify-content',
    c: 'align-items',
    d: 'vertical-align',
    answer: 'a',
    explanation: '`text-align: center;` được dùng để căn giữa nội dung theo chiều ngang.'
  },
  {
    content: 'Giao thức nào đảm bảo việc truyền dữ liệu trên Internet được bảo mật?',
    type: 'SINGLE_CHOICE',
    a: 'HTTP',
    b: 'FTP',
    c: 'HTTPS',
    d: 'SMTP',
    answer: 'c',
    explanation: 'HTTPS là phiên bản an toàn của HTTP, sử dụng mã hóa để bảo mật dữ liệu.'
  },
  {
    content: 'Trong Node.js, module nào dùng để làm việc với hệ thống tệp?',
    type: 'SINGLE_CHOICE',
    a: 'os',
    b: 'path',
    c: 'fs',
    d: 'http',
    answer: 'c',
    explanation: 'Module `fs` cung cấp các hàm để làm việc với hệ thống tệp trong Node.js.'
  },
  {
    content: 'Trong MongoDB, phương thức nào được dùng để chèn nhiều tài liệu vào một collection?',
    type: 'SINGLE_CHOICE',
    a: 'insert()',
    b: 'insertOne()',
    c: 'insertMany()',
    d: 'bulkInsert()',
    answer: 'c',
    explanation: '`insertMany()` được dùng để chèn nhiều tài liệu vào một collection.'
  },
  {
    content: 'Ngôn ngữ lập trình nào chủ yếu được dùng để phát triển ứng dụng Android?',
    type: 'SINGLE_CHOICE',
    a: 'Swift',
    b: 'Kotlin',
    c: 'C#',
    d: 'Ruby',
    answer: 'b',
    explanation: 'Kotlin là ngôn ngữ chính thức để phát triển ứng dụng Android.'
  },
  {
    content: 'Hàm nào trong JavaScript trả về độ dài của một chuỗi?',
    type: 'SINGLE_CHOICE',
    a: 'length()',
    b: 'size()',
    c: 'length',
    d: 'count()',
    answer: 'c',
    explanation: 'Thuộc tính `length` của chuỗi trả về số ký tự trong chuỗi.'
  },
  {
    content: 'Ký hiệu nào được dùng để khai báo biến trong JavaScript?',
    type: 'SINGLE_CHOICE',
    a: 'var',
    b: 'let',
    c: 'const',
    d: 'Tất cả các đáp án trên',
    answer: 'd',
    explanation: 'Trong JavaScript, bạn có thể dùng `var`, `let` hoặc `const` để khai báo biến.'
  },
  {
    content: 'Trong hệ điều hành Linux, lệnh nào được dùng để liệt kê các tệp trong thư mục?',
    type: 'SINGLE_CHOICE',
    a: 'dir',
    b: 'list',
    c: 'ls',
    d: 'show',
    answer: 'c',
    explanation: 'Lệnh `ls` liệt kê tất cả các tệp và thư mục trong thư mục hiện tại.'
  },
  {
    content: 'Phương thức HTTP nào thường được sử dụng để gửi dữ liệu đến máy chủ?',
    type: 'SINGLE_CHOICE',
    a: 'GET',
    b: 'POST',
    c: 'PUT',
    d: 'DELETE',
    answer: 'b',
    explanation: 'Phương thức POST được dùng để gửi dữ liệu đến máy chủ.'
  },
  {
    content: 'Thành phần nào của máy tính thực hiện các phép toán và logic?',
    type: 'SINGLE_CHOICE',
    a: 'RAM',
    b: 'CPU',
    c: 'Hard Drive',
    d: 'Power Supply',
    answer: 'b',
    explanation: 'CPU (Central Processing Unit) là thành phần thực hiện các phép toán và logic.'
  },
  {
    content: 'Hàm nào trong PHP dùng để nối chuỗi?',
    type: 'SINGLE_CHOICE',
    a: 'concat()',
    b: 'join()',
    c: '. (dấu chấm)',
    d: 'append()',
    answer: 'c',
    explanation: 'Trong PHP, dấu `.` được dùng để nối chuỗi.'
  },
  {
    content: 'Hàm nào trong Python trả về số phần tử của một danh sách?',
    type: 'SINGLE_CHOICE',
    a: 'size()',
    b: 'count()',
    c: 'length()',
    d: 'len()',
    answer: 'd',
    explanation: 'Hàm `len()` trả về số phần tử trong danh sách.'
  },
  {
    content: 'Trong SQL, từ khóa nào dùng để lọc các bản ghi trùng lặp?',
    type: 'SINGLE_CHOICE',
    a: 'UNIQUE',
    b: 'DISTINCT',
    c: 'LIMIT',
    d: 'GROUP BY',
    answer: 'b',
    explanation: '`DISTINCT` được dùng để loại bỏ các bản ghi trùng lặp trong kết quả.'
  },
  {
    content: 'Thẻ nào trong HTML5 được dùng để phát video?',
    type: 'SINGLE_CHOICE',
    a: '<audio>',
    b: '<video>',
    c: '<media>',
    d: '<source>',
    answer: 'b',
    explanation: 'Thẻ `<video>` trong HTML5 được dùng để phát video.'
  },
  {
    content: 'Công cụ nào phổ biến để quản lý phiên bản mã nguồn?',
    type: 'SINGLE_CHOICE',
    a: 'Git',
    b: 'SVN',
    c: 'Mercurial',
    d: 'Tất cả các đáp án trên',
    answer: 'd',
    explanation: 'Git, SVN và Mercurial đều là các công cụ quản lý phiên bản mã nguồn.'
  },
  {
    content: 'Ngôn ngữ lập trình nào sau đây thường được sử dụng để phát triển ứng dụng web front-end?',
    type: 'MULTIPLE_CHOICE',
    a: 'Java',
    b: 'Python',
    c: 'JavaScript',
    d: 'C++',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a::b::c',
    explanation: 'JavaScript là ngôn ngữ lập trình chính được sử dụng để phát triển giao diện người dùng của website, trong khi Java và Python thường dùng cho backend, C++ cho các ứng dụng hệ thống.'
  },
  {
    content: 'Đâu là một hệ quản trị cơ sở dữ liệu quan hệ?',
    type: 'SINGLE_CHOICE',
    a: 'MySQL',
    b: 'MongoDB',
    c: 'Redis',
    d: 'Cassandra',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a',
    explanation: 'MySQL là một hệ quản trị cơ sở dữ liệu quan hệ, trong khi MongoDB, Redis, và Cassandra là các hệ quản trị cơ sở dữ liệu NoSQL.'
  },
  {
    content: "Thuật ngữ 'API' thường được viết tắt cho điều gì trong IT?",
    type: 'SINGLE_CHOICE',
    a: 'Advanced Programming Interface',
    b: 'Application Programming Interface',
    c: 'Application Process Integration',
    d: 'Advanced Process Integration',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'b',
    explanation: 'API là viết tắt của Application Programming Interface, một tập hợp các định nghĩa và giao thức để xây dựng và tích hợp phần mềm ứng dụng.'
  },
  {
    content: 'Trong mô hình OSI, tầng nào chịu trách nhiệm định tuyến dữ liệu giữa các mạng?',
    type: 'SINGLE_CHOICE',
    a: 'Tầng Vật lý (Physical Layer)',
    b: 'Tầng Mạng (Network Layer)',
    c: 'Tầng Vận chuyển (Transport Layer)',
    d: 'Tầng Ứng dụng (Application Layer)',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'b',
    explanation: 'Tầng Mạng (Network Layer) trong mô hình OSI chịu trách nhiệm định tuyến dữ liệu giữa các mạng khác nhau.'
  },
  {
    content: 'Ngôn ngữ nào thường được sử dụng cho các ứng dụng khoa học dữ liệu và học máy?',
    type: 'SINGLE_CHOICE',
    a: 'PHP',
    b: 'Ruby',
    c: 'Python',
    d: 'Swift',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Python là ngôn ngữ phổ biến nhất trong khoa học dữ liệu và học máy nhờ thư viện phong phú và cú pháp dễ đọc.'
  },
  {
    content: "Khái niệm 'RESTful' thường được liên kết với loại kiến trúc nào?",
    type: 'SINGLE_CHOICE',
    a: 'Kiến trúc hướng sự kiện',
    b: 'Kiến trúc Microservices',
    c: 'Kiến trúc Dịch vụ Web',
    d: 'Kiến trúc Máy chủ - Client',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'RESTful thường được liên kết với kiến trúc Dịch vụ Web (Web Services) để thiết kế các API.'
  },
  {
    content: 'Trong hệ điều hành Linux, lệnh nào sau đây được sử dụng để thay đổi quyền truy cập của tệp?',
    type: 'SINGLE_CHOICE',
    a: 'chmod',
    b: 'chown',
    c: 'chgrp',
    d: 'sudo',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a',
    explanation: 'Lệnh chmod được sử dụng để thay đổi quyền truy cập (đọc, viết, thực thi) của các tập tin và thư mục trên Linux.'
  },
  {
    content: 'Đâu là một framework phổ biến cho phát triển ứng dụng web bằng Python?',
    type: 'SINGLE_CHOICE',
    a: 'React',
    b: 'Angular',
    c: 'Django',
    d: 'Vue.js',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Django là một framework web phổ biến cho Python, trong khi React, Angular, và Vue.js thường được sử dụng cho front-end.'
  },
  {
    content: 'Công cụ nào sau đây thường được dùng để container hóa ứng dụng?',
    type: 'SINGLE_CHOICE',
    a: 'npm',
    b: 'pip',
    c: 'Docker',
    d: 'Maven',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Docker là một nền tảng phổ biến để xây dựng, triển khai và quản lý các ứng dụng container.'
  },
  {
    content: "Thuật ngữ 'Cloud Computing' dùng để chỉ điều gì?",
    type: 'SINGLE_CHOICE',
    a: 'Việc phát triển phần mềm trên các thiết bị di động',
    b: 'Việc sử dụng các máy tính cá nhân để lưu trữ dữ liệu',
    c: 'Việc cung cấp tài nguyên điện toán qua internet',
    d: 'Việc tạo các mạng cục bộ',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Cloud Computing đề cập đến việc cung cấp các dịch vụ điện toán như máy chủ, lưu trữ, cơ sở dữ liệu qua Internet.'
  },
  {
    content: 'Công nghệ nào sau đây thường được sử dụng để xây dựng các trang web động?',
    type: 'SINGLE_CHOICE',
    a: 'HTML',
    b: 'CSS',
    c: 'JavaScript',
    d: 'XML',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'JavaScript được sử dụng rộng rãi để tạo các trang web động, tương tác và thực hiện các chức năng phía client-side.'
  },
  {
    content: "Trong lập trình hướng đối tượng, 'kế thừa' có nghĩa là gì?",
    type: 'SINGLE_CHOICE',
    a: 'Một đối tượng có thể chứa nhiều đối tượng khác',
    b: 'Một đối tượng có thể tạo ra một bản sao mới của chính nó',
    c: 'Một đối tượng có thể sử dụng lại các thuộc tính và phương thức của đối tượng khác',
    d: 'Một đối tượng có thể thay đổi trạng thái của đối tượng khác',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Kế thừa cho phép một lớp (đối tượng) có thể sử dụng các thuộc tính và phương thức của một lớp (đối tượng) khác, tạo ra mối quan hệ phân cấp.'
  },
  {
    content: "Trong mạng máy tính, 'IP address' là gì?",
    type: 'SINGLE_CHOICE',
    a: 'Địa chỉ vật lý của thiết bị',
    b: 'Địa chỉ logic của thiết bị trên mạng',
    c: 'Tên của thiết bị',
    d: 'Mật khẩu của thiết bị',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'b',
    explanation: 'Địa chỉ IP (Internet Protocol address) là một địa chỉ logic để xác định thiết bị trên mạng.'
  },
  {
    content: 'Công nghệ nào thường được sử dụng để quản lý và phân tích dữ liệu lớn (Big Data)?',
    type: 'SINGLE_CHOICE',
    a: 'Microsoft Access',
    b: 'Excel',
    c: 'Hadoop',
    d: 'MySQL',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Hadoop là một framework phổ biến để xử lý và phân tích dữ liệu lớn.'
  },
  {
    content: 'Trong JavaScript, phương thức nào được sử dụng để thêm phần tử vào cuối mảng?',
    type: 'SINGLE_CHOICE',
    a: 'push()',
    b: 'pop()',
    c: 'shift()',
    d: 'unshift()',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a',
    explanation: 'Phương thức push() được sử dụng để thêm phần tử mới vào cuối mảng trong JavaScript.'
  },
  {
    content: 'Giao thức nào được sử dụng để gửi email?',
    type: 'SINGLE_CHOICE',
    a: 'HTTP',
    b: 'SMTP',
    c: 'FTP',
    d: 'IMAP',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'b',
    explanation: 'SMTP (Simple Mail Transfer Protocol) được sử dụng để gửi email.'
  },
  {
    content: 'Công cụ nào sau đây được sử dụng để quản lý các package trong Node.js?',
    type: 'SINGLE_CHOICE',
    a: 'npm',
    b: 'pip',
    c: 'yarn',
    d: 'composer',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a',
    explanation: 'npm (Node Package Manager) là công cụ quản lý package mặc định của Node.js.'
  },
  {
    content: 'Đâu là một hệ điều hành mã nguồn mở phổ biến?',
    type: 'SINGLE_CHOICE',
    a: 'Windows',
    b: 'Linux',
    c: 'macOS',
    d: 'iOS',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'b',
    explanation: 'Linux là một hệ điều hành mã nguồn mở phổ biến được sử dụng rộng rãi.'
  },
  {
    content: 'Công cụ nào được sử dụng để kiểm tra và phát hiện lỗi của các trang web?',
    type: 'SINGLE_CHOICE',
    a: 'Postman',
    b: 'Jenkins',
    c: 'Selenium',
    d: 'Docker',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Selenium là công cụ tự động hóa phổ biến để kiểm tra và phát hiện lỗi trên các trang web.'
  },
  {
    content: 'Trong JavaScript, từ khóa nào được sử dụng để khai báo một biến không thể thay đổi?',
    type: 'SINGLE_CHOICE',
    a: 'var',
    b: 'let',
    c: 'const',
    d: 'static',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Từ khóa const trong JavaScript được sử dụng để khai báo biến không thể thay đổi giá trị.'
  },
  {
    content: 'Đâu là công cụ phổ biến để quản lý phiên bản mã nguồn?',
    type: 'SINGLE_CHOICE',
    a: 'Git',
    b: 'Node.js',
    c: 'PHP',
    d: 'MySQL',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a',
    explanation: 'Git là công cụ kiểm soát phiên bản được sử dụng rộng rãi trong phát triển phần mềm.'
  },
  {
    content: 'JavaScript thuộc kiểu ngôn ngữ nào?',
    type: 'SINGLE_CHOICE',
    a: 'Ngôn ngữ lập trình hướng đối tượng',
    b: 'Ngôn ngữ kịch bản',
    c: 'Ngôn ngữ lập trình biên dịch',
    d: 'Ngôn ngữ lập trình chức năng',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'b',
    explanation: 'JavaScript là một ngôn ngữ kịch bản chủ yếu chạy trên trình duyệt web.'
  },
  {
    content: 'Câu lệnh nào trong SQL dùng để xóa dữ liệu từ bảng?',
    type: 'SINGLE_CHOICE',
    a: 'DELETE',
    b: 'DROP',
    c: 'REMOVE',
    d: 'CLEAR',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a',
    explanation: 'Câu lệnh DELETE được sử dụng để xóa dữ liệu từ một bảng trong cơ sở dữ liệu SQL.'
  },
  {
    content: 'Lệnh nào dùng để kiểm tra trạng thái của Git repository?',
    type: 'SINGLE_CHOICE',
    a: 'git log',
    b: 'git branch',
    c: 'git status',
    d: 'git commit',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Lệnh `git status` hiển thị thông tin về trạng thái hiện tại của Git repository.'
  },
  {
    content: 'Trong HTML, thuộc tính nào dùng để đặt đường dẫn của hình ảnh?',
    type: 'SINGLE_CHOICE',
    a: 'alt',
    b: 'href',
    c: 'src',
    d: 'path',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Thuộc tính `src` trong HTML dùng để đặt đường dẫn của hình ảnh.'
  },
  {
    content: 'Framework nào sau đây được sử dụng để xây dựng giao diện người dùng trên web?',
    type: 'SINGLE_CHOICE',
    a: 'Django',
    b: 'React',
    c: 'Flask',
    d: 'Laravel',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'b',
    explanation: 'React là một thư viện JavaScript được sử dụng để xây dựng giao diện người dùng.'
  },
  {
    content: 'Phương thức nào dùng để chuyển một chuỗi thành chữ in hoa trong JavaScript?',
    type: 'SINGLE_CHOICE',
    a: 'toUpperCase()',
    b: 'toLowerCase()',
    c: 'toString()',
    d: 'charAt()',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a',
    explanation: 'Phương thức `toUpperCase()` trong JavaScript được sử dụng để chuyển đổi chuỗi thành chữ in hoa.'
  },
  {
    content: 'Trong CSS, thuộc tính nào dùng để thay đổi màu chữ?',
    type: 'SINGLE_CHOICE',
    a: 'color',
    b: 'background-color',
    c: 'font-color',
    d: 'text-color',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a',
    explanation: 'Thuộc tính `color` trong CSS dùng để thay đổi màu chữ.'
  },
  {
    content: 'Phương thức nào trong JavaScript dùng để kiểm tra xem một chuỗi có bắt đầu bằng một chuỗi con cụ thể không?',
    type: 'SINGLE_CHOICE',
    a: 'includes()',
    b: 'startsWith()',
    c: 'endsWith()',
    d: 'indexOf()',
    answer: 'b',
    explanation: '`startsWith()` kiểm tra chuỗi có bắt đầu bằng chuỗi con được chỉ định không.'
  },
  {
    content: 'Lệnh nào dùng để tạo một bảng mới trong SQL?',
    type: 'SINGLE_CHOICE',
    a: 'CREATE TABLE',
    b: 'INSERT INTO',
    c: 'ALTER TABLE',
    d: 'NEW TABLE',
    answer: 'a',
    explanation: '`CREATE TABLE` được dùng để tạo bảng mới trong cơ sở dữ liệu.'
  },
  {
    content: 'Trong HTML, thẻ nào dùng để tạo danh sách có thứ tự?',
    type: 'SINGLE_CHOICE',
    a: '<ul>',
    b: '<ol>',
    c: '<li>',
    d: '<dl>',
    answer: 'b',
    explanation: 'Thẻ `<ol>` được dùng để tạo danh sách có thứ tự.'
  },
  {
    content: 'Trong React, hook nào được sử dụng để quản lý trạng thái của component?',
    type: 'SINGLE_CHOICE',
    a: 'useEffect',
    b: 'useState',
    c: 'useContext',
    d: 'useReducer',
    answer: 'b',
    explanation: '`useState` là hook dùng để quản lý trạng thái trong React function component.'
  },
  {
    content: 'Hàm nào trong Python dùng để sắp xếp một danh sách?',
    type: 'SINGLE_CHOICE',
    a: 'sort()',
    b: 'sorted()',
    c: 'arrange()',
    d: 'order()',
    answer: 'b',
    explanation: '`sorted()` là hàm tích hợp trong Python dùng để sắp xếp danh sách.'
  },
  {
    content: 'Thuộc tính nào của CSS dùng để căn giữa nội dung theo chiều ngang?',
    type: 'SINGLE_CHOICE',
    a: 'text-align',
    b: 'justify-content',
    c: 'align-items',
    d: 'vertical-align',
    answer: 'a',
    explanation: '`text-align: center;` được dùng để căn giữa nội dung theo chiều ngang.'
  },
  {
    content: 'Giao thức nào đảm bảo việc truyền dữ liệu trên Internet được bảo mật?',
    type: 'SINGLE_CHOICE',
    a: 'HTTP',
    b: 'FTP',
    c: 'HTTPS',
    d: 'SMTP',
    answer: 'c',
    explanation: 'HTTPS là phiên bản an toàn của HTTP, sử dụng mã hóa để bảo mật dữ liệu.'
  },
  {
    content: 'Trong Node.js, module nào dùng để làm việc với hệ thống tệp?',
    type: 'SINGLE_CHOICE',
    a: 'os',
    b: 'path',
    c: 'fs',
    d: 'http',
    answer: 'c',
    explanation: 'Module `fs` cung cấp các hàm để làm việc với hệ thống tệp trong Node.js.'
  },
  {
    content: 'Trong MongoDB, phương thức nào được dùng để chèn nhiều tài liệu vào một collection?',
    type: 'SINGLE_CHOICE',
    a: 'insert()',
    b: 'insertOne()',
    c: 'insertMany()',
    d: 'bulkInsert()',
    answer: 'c',
    explanation: '`insertMany()` được dùng để chèn nhiều tài liệu vào một collection.'
  },
  {
    content: 'Ngôn ngữ lập trình nào chủ yếu được dùng để phát triển ứng dụng Android?',
    type: 'SINGLE_CHOICE',
    a: 'Swift',
    b: 'Kotlin',
    c: 'C#',
    d: 'Ruby',
    answer: 'b',
    explanation: 'Kotlin là ngôn ngữ chính thức để phát triển ứng dụng Android.'
  },
  {
    content: 'Hàm nào trong JavaScript trả về độ dài của một chuỗi?',
    type: 'SINGLE_CHOICE',
    a: 'length()',
    b: 'size()',
    c: 'length',
    d: 'count()',
    answer: 'c',
    explanation: 'Thuộc tính `length` của chuỗi trả về số ký tự trong chuỗi.'
  },
  {
    content: 'Ký hiệu nào được dùng để khai báo biến trong JavaScript?',
    type: 'SINGLE_CHOICE',
    a: 'var',
    b: 'let',
    c: 'const',
    d: 'Tất cả các đáp án trên',
    answer: 'd',
    explanation: 'Trong JavaScript, bạn có thể dùng `var`, `let` hoặc `const` để khai báo biến.'
  },
  {
    content: 'Trong hệ điều hành Linux, lệnh nào được dùng để liệt kê các tệp trong thư mục?',
    type: 'SINGLE_CHOICE',
    a: 'dir',
    b: 'list',
    c: 'ls',
    d: 'show',
    answer: 'c',
    explanation: 'Lệnh `ls` liệt kê tất cả các tệp và thư mục trong thư mục hiện tại.'
  },
  {
    content: 'Phương thức HTTP nào thường được sử dụng để gửi dữ liệu đến máy chủ?',
    type: 'SINGLE_CHOICE',
    a: 'GET',
    b: 'POST',
    c: 'PUT',
    d: 'DELETE',
    answer: 'b',
    explanation: 'Phương thức POST được dùng để gửi dữ liệu đến máy chủ.'
  },
  {
    content: 'Thành phần nào của máy tính thực hiện các phép toán và logic?',
    type: 'SINGLE_CHOICE',
    a: 'RAM',
    b: 'CPU',
    c: 'Hard Drive',
    d: 'Power Supply',
    answer: 'b',
    explanation: 'CPU (Central Processing Unit) là thành phần thực hiện các phép toán và logic.'
  },
  {
    content: 'Hàm nào trong PHP dùng để nối chuỗi?',
    type: 'SINGLE_CHOICE',
    a: 'concat()',
    b: 'join()',
    c: '. (dấu chấm)',
    d: 'append()',
    answer: 'c',
    explanation: 'Trong PHP, dấu `.` được dùng để nối chuỗi.'
  },
  {
    content: 'Hàm nào trong Python trả về số phần tử của một danh sách?',
    type: 'SINGLE_CHOICE',
    a: 'size()',
    b: 'count()',
    c: 'length()',
    d: 'len()',
    answer: 'd',
    explanation: 'Hàm `len()` trả về số phần tử trong danh sách.'
  },
  {
    content: 'Trong SQL, từ khóa nào dùng để lọc các bản ghi trùng lặp?',
    type: 'SINGLE_CHOICE',
    a: 'UNIQUE',
    b: 'DISTINCT',
    c: 'LIMIT',
    d: 'GROUP BY',
    answer: 'b',
    explanation: '`DISTINCT` được dùng để loại bỏ các bản ghi trùng lặp trong kết quả.'
  },
  {
    content: 'Thẻ nào trong HTML5 được dùng để phát video?',
    type: 'SINGLE_CHOICE',
    a: '<audio>',
    b: '<video>',
    c: '<media>',
    d: '<source>',
    answer: 'b',
    explanation: 'Thẻ `<video>` trong HTML5 được dùng để phát video.'
  },
  {
    content: 'Công cụ nào phổ biến để quản lý phiên bản mã nguồn?',
    type: 'SINGLE_CHOICE',
    a: 'Git',
    b: 'SVN',
    c: 'Mercurial',
    d: 'Tất cả các đáp án trên',
    answer: 'd',
    explanation: 'Git, SVN và Mercurial đều là các công cụ quản lý phiên bản mã nguồn.'
  },
  {
    content: 'Ngôn ngữ lập trình nào sau đây thường được sử dụng để phát triển ứng dụng web front-end?',
    type: 'MULTIPLE_CHOICE',
    a: 'Java',
    b: 'Python',
    c: 'JavaScript',
    d: 'C++',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a::b::c',
    explanation: 'JavaScript là ngôn ngữ lập trình chính được sử dụng để phát triển giao diện người dùng của website, trong khi Java và Python thường dùng cho backend, C++ cho các ứng dụng hệ thống.'
  },
  {
    content: 'Đâu là một hệ quản trị cơ sở dữ liệu quan hệ?',
    type: 'SINGLE_CHOICE',
    a: 'MySQL',
    b: 'MongoDB',
    c: 'Redis',
    d: 'Cassandra',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a',
    explanation: 'MySQL là một hệ quản trị cơ sở dữ liệu quan hệ, trong khi MongoDB, Redis, và Cassandra là các hệ quản trị cơ sở dữ liệu NoSQL.'
  },
  {
    content: "Thuật ngữ 'API' thường được viết tắt cho điều gì trong IT?",
    type: 'SINGLE_CHOICE',
    a: 'Advanced Programming Interface',
    b: 'Application Programming Interface',
    c: 'Application Process Integration',
    d: 'Advanced Process Integration',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'b',
    explanation: 'API là viết tắt của Application Programming Interface, một tập hợp các định nghĩa và giao thức để xây dựng và tích hợp phần mềm ứng dụng.'
  },
  {
    content: 'Trong mô hình OSI, tầng nào chịu trách nhiệm định tuyến dữ liệu giữa các mạng?',
    type: 'SINGLE_CHOICE',
    a: 'Tầng Vật lý (Physical Layer)',
    b: 'Tầng Mạng (Network Layer)',
    c: 'Tầng Vận chuyển (Transport Layer)',
    d: 'Tầng Ứng dụng (Application Layer)',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'b',
    explanation: 'Tầng Mạng (Network Layer) trong mô hình OSI chịu trách nhiệm định tuyến dữ liệu giữa các mạng khác nhau.'
  },
  {
    content: 'Ngôn ngữ nào thường được sử dụng cho các ứng dụng khoa học dữ liệu và học máy?',
    type: 'SINGLE_CHOICE',
    a: 'PHP',
    b: 'Ruby',
    c: 'Python',
    d: 'Swift',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Python là ngôn ngữ phổ biến nhất trong khoa học dữ liệu và học máy nhờ thư viện phong phú và cú pháp dễ đọc.'
  },
  {
    content: "Khái niệm 'RESTful' thường được liên kết với loại kiến trúc nào?",
    type: 'SINGLE_CHOICE',
    a: 'Kiến trúc hướng sự kiện',
    b: 'Kiến trúc Microservices',
    c: 'Kiến trúc Dịch vụ Web',
    d: 'Kiến trúc Máy chủ - Client',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'RESTful thường được liên kết với kiến trúc Dịch vụ Web (Web Services) để thiết kế các API.'
  },
  {
    content: 'Trong hệ điều hành Linux, lệnh nào sau đây được sử dụng để thay đổi quyền truy cập của tệp?',
    type: 'SINGLE_CHOICE',
    a: 'chmod',
    b: 'chown',
    c: 'chgrp',
    d: 'sudo',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a',
    explanation: 'Lệnh chmod được sử dụng để thay đổi quyền truy cập (đọc, viết, thực thi) của các tập tin và thư mục trên Linux.'
  },
  {
    content: 'Đâu là một framework phổ biến cho phát triển ứng dụng web bằng Python?',
    type: 'SINGLE_CHOICE',
    a: 'React',
    b: 'Angular',
    c: 'Django',
    d: 'Vue.js',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Django là một framework web phổ biến cho Python, trong khi React, Angular, và Vue.js thường được sử dụng cho front-end.'
  },
  {
    content: 'Công cụ nào sau đây thường được dùng để container hóa ứng dụng?',
    type: 'SINGLE_CHOICE',
    a: 'npm',
    b: 'pip',
    c: 'Docker',
    d: 'Maven',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Docker là một nền tảng phổ biến để xây dựng, triển khai và quản lý các ứng dụng container.'
  },
  {
    content: "Thuật ngữ 'Cloud Computing' dùng để chỉ điều gì?",
    type: 'SINGLE_CHOICE',
    a: 'Việc phát triển phần mềm trên các thiết bị di động',
    b: 'Việc sử dụng các máy tính cá nhân để lưu trữ dữ liệu',
    c: 'Việc cung cấp tài nguyên điện toán qua internet',
    d: 'Việc tạo các mạng cục bộ',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Cloud Computing đề cập đến việc cung cấp các dịch vụ điện toán như máy chủ, lưu trữ, cơ sở dữ liệu qua Internet.'
  },
  {
    content: 'Công nghệ nào sau đây thường được sử dụng để xây dựng các trang web động?',
    type: 'SINGLE_CHOICE',
    a: 'HTML',
    b: 'CSS',
    c: 'JavaScript',
    d: 'XML',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'JavaScript được sử dụng rộng rãi để tạo các trang web động, tương tác và thực hiện các chức năng phía client-side.'
  },
  {
    content: "Trong lập trình hướng đối tượng, 'kế thừa' có nghĩa là gì?",
    type: 'SINGLE_CHOICE',
    a: 'Một đối tượng có thể chứa nhiều đối tượng khác',
    b: 'Một đối tượng có thể tạo ra một bản sao mới của chính nó',
    c: 'Một đối tượng có thể sử dụng lại các thuộc tính và phương thức của đối tượng khác',
    d: 'Một đối tượng có thể thay đổi trạng thái của đối tượng khác',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Kế thừa cho phép một lớp (đối tượng) có thể sử dụng các thuộc tính và phương thức của một lớp (đối tượng) khác, tạo ra mối quan hệ phân cấp.'
  },
  {
    content: "Trong mạng máy tính, 'IP address' là gì?",
    type: 'SINGLE_CHOICE',
    a: 'Địa chỉ vật lý của thiết bị',
    b: 'Địa chỉ logic của thiết bị trên mạng',
    c: 'Tên của thiết bị',
    d: 'Mật khẩu của thiết bị',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'b',
    explanation: 'Địa chỉ IP (Internet Protocol address) là một địa chỉ logic để xác định thiết bị trên mạng.'
  },
  {
    content: 'Công nghệ nào thường được sử dụng để quản lý và phân tích dữ liệu lớn (Big Data)?',
    type: 'SINGLE_CHOICE',
    a: 'Microsoft Access',
    b: 'Excel',
    c: 'Hadoop',
    d: 'MySQL',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Hadoop là một framework phổ biến để xử lý và phân tích dữ liệu lớn.'
  },
  {
    content: 'Trong JavaScript, phương thức nào được sử dụng để thêm phần tử vào cuối mảng?',
    type: 'SINGLE_CHOICE',
    a: 'push()',
    b: 'pop()',
    c: 'shift()',
    d: 'unshift()',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a',
    explanation: 'Phương thức push() được sử dụng để thêm phần tử mới vào cuối mảng trong JavaScript.'
  },
  {
    content: 'Giao thức nào được sử dụng để gửi email?',
    type: 'SINGLE_CHOICE',
    a: 'HTTP',
    b: 'SMTP',
    c: 'FTP',
    d: 'IMAP',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'b',
    explanation: 'SMTP (Simple Mail Transfer Protocol) được sử dụng để gửi email.'
  },
  {
    content: 'Công cụ nào sau đây được sử dụng để quản lý các package trong Node.js?',
    type: 'SINGLE_CHOICE',
    a: 'npm',
    b: 'pip',
    c: 'yarn',
    d: 'composer',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a',
    explanation: 'npm (Node Package Manager) là công cụ quản lý package mặc định của Node.js.'
  },
  {
    content: 'Đâu là một hệ điều hành mã nguồn mở phổ biến?',
    type: 'SINGLE_CHOICE',
    a: 'Windows',
    b: 'Linux',
    c: 'macOS',
    d: 'iOS',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'b',
    explanation: 'Linux là một hệ điều hành mã nguồn mở phổ biến được sử dụng rộng rãi.'
  },
  {
    content: 'Công cụ nào được sử dụng để kiểm tra và phát hiện lỗi của các trang web?',
    type: 'SINGLE_CHOICE',
    a: 'Postman',
    b: 'Jenkins',
    c: 'Selenium',
    d: 'Docker',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Selenium là công cụ tự động hóa phổ biến để kiểm tra và phát hiện lỗi trên các trang web.'
  },
  {
    content: 'Trong JavaScript, từ khóa nào được sử dụng để khai báo một biến không thể thay đổi?',
    type: 'SINGLE_CHOICE',
    a: 'var',
    b: 'let',
    c: 'const',
    d: 'static',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Từ khóa const trong JavaScript được sử dụng để khai báo biến không thể thay đổi giá trị.'
  },
  {
    content: 'Đâu là công cụ phổ biến để quản lý phiên bản mã nguồn?',
    type: 'SINGLE_CHOICE',
    a: 'Git',
    b: 'Node.js',
    c: 'PHP',
    d: 'MySQL',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a',
    explanation: 'Git là công cụ kiểm soát phiên bản được sử dụng rộng rãi trong phát triển phần mềm.'
  },
  {
    content: 'JavaScript thuộc kiểu ngôn ngữ nào?',
    type: 'SINGLE_CHOICE',
    a: 'Ngôn ngữ lập trình hướng đối tượng',
    b: 'Ngôn ngữ kịch bản',
    c: 'Ngôn ngữ lập trình biên dịch',
    d: 'Ngôn ngữ lập trình chức năng',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'b',
    explanation: 'JavaScript là một ngôn ngữ kịch bản chủ yếu chạy trên trình duyệt web.'
  },
  {
    content: 'Câu lệnh nào trong SQL dùng để xóa dữ liệu từ bảng?',
    type: 'SINGLE_CHOICE',
    a: 'DELETE',
    b: 'DROP',
    c: 'REMOVE',
    d: 'CLEAR',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a',
    explanation: 'Câu lệnh DELETE được sử dụng để xóa dữ liệu từ một bảng trong cơ sở dữ liệu SQL.'
  },
  {
    content: 'Lệnh nào dùng để kiểm tra trạng thái của Git repository?',
    type: 'SINGLE_CHOICE',
    a: 'git log',
    b: 'git branch',
    c: 'git status',
    d: 'git commit',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Lệnh `git status` hiển thị thông tin về trạng thái hiện tại của Git repository.'
  },
  {
    content: 'Trong HTML, thuộc tính nào dùng để đặt đường dẫn của hình ảnh?',
    type: 'SINGLE_CHOICE',
    a: 'alt',
    b: 'href',
    c: 'src',
    d: 'path',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'c',
    explanation: 'Thuộc tính `src` trong HTML dùng để đặt đường dẫn của hình ảnh.'
  },
  {
    content: 'Framework nào sau đây được sử dụng để xây dựng giao diện người dùng trên web?',
    type: 'SINGLE_CHOICE',
    a: 'Django',
    b: 'React',
    c: 'Flask',
    d: 'Laravel',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'b',
    explanation: 'React là một thư viện JavaScript được sử dụng để xây dựng giao diện người dùng.'
  },
  {
    content: 'Phương thức nào dùng để chuyển một chuỗi thành chữ in hoa trong JavaScript?',
    type: 'SINGLE_CHOICE',
    a: 'toUpperCase()',
    b: 'toLowerCase()',
    c: 'toString()',
    d: 'charAt()',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a',
    explanation: 'Phương thức `toUpperCase()` trong JavaScript được sử dụng để chuyển đổi chuỗi thành chữ in hoa.'
  },
  {
    content: 'Trong CSS, thuộc tính nào dùng để thay đổi màu chữ?',
    type: 'SINGLE_CHOICE',
    a: 'color',
    b: 'background-color',
    c: 'font-color',
    d: 'text-color',
    e: '',
    f: '',
    g: '',
    h: '',
    i: '',
    j: '',
    k: '',
    l: '',
    m: '',
    n: '',
    o: '',
    p: '',
    answer: 'a',
    explanation: 'Thuộc tính `color` trong CSS dùng để thay đổi màu chữ.'
  },
  {
    content: 'Phương thức nào trong JavaScript dùng để kiểm tra xem một chuỗi có bắt đầu bằng một chuỗi con cụ thể không?',
    type: 'SINGLE_CHOICE',
    a: 'includes()',
    b: 'startsWith()',
    c: 'endsWith()',
    d: 'indexOf()',
    answer: 'b',
    explanation: '`startsWith()` kiểm tra chuỗi có bắt đầu bằng chuỗi con được chỉ định không.'
  },
  {
    content: 'Lệnh nào dùng để tạo một bảng mới trong SQL?',
    type: 'SINGLE_CHOICE',
    a: 'CREATE TABLE',
    b: 'INSERT INTO',
    c: 'ALTER TABLE',
    d: 'NEW TABLE',
    answer: 'a',
    explanation: '`CREATE TABLE` được dùng để tạo bảng mới trong cơ sở dữ liệu.'
  },
  {
    content: 'Trong HTML, thẻ nào dùng để tạo danh sách có thứ tự?',
    type: 'SINGLE_CHOICE',
    a: '<ul>',
    b: '<ol>',
    c: '<li>',
    d: '<dl>',
    answer: 'b',
    explanation: 'Thẻ `<ol>` được dùng để tạo danh sách có thứ tự.'
  },
  {
    content: 'Trong React, hook nào được sử dụng để quản lý trạng thái của component?',
    type: 'SINGLE_CHOICE',
    a: 'useEffect',
    b: 'useState',
    c: 'useContext',
    d: 'useReducer',
    answer: 'b',
    explanation: '`useState` là hook dùng để quản lý trạng thái trong React function component.'
  },
  {
    content: 'Hàm nào trong Python dùng để sắp xếp một danh sách?',
    type: 'SINGLE_CHOICE',
    a: 'sort()',
    b: 'sorted()',
    c: 'arrange()',
    d: 'order()',
    answer: 'b',
    explanation: '`sorted()` là hàm tích hợp trong Python dùng để sắp xếp danh sách.'
  },
  {
    content: 'Thuộc tính nào của CSS dùng để căn giữa nội dung theo chiều ngang?',
    type: 'SINGLE_CHOICE',
    a: 'text-align',
    b: 'justify-content',
    c: 'align-items',
    d: 'vertical-align',
    answer: 'a',
    explanation: '`text-align: center;` được dùng để căn giữa nội dung theo chiều ngang.'
  },
  {
    content: 'Giao thức nào đảm bảo việc truyền dữ liệu trên Internet được bảo mật?',
    type: 'SINGLE_CHOICE',
    a: 'HTTP',
    b: 'FTP',
    c: 'HTTPS',
    d: 'SMTP',
    answer: 'c',
    explanation: 'HTTPS là phiên bản an toàn của HTTP, sử dụng mã hóa để bảo mật dữ liệu.'
  },
  {
    content: 'Trong Node.js, module nào dùng để làm việc với hệ thống tệp?',
    type: 'SINGLE_CHOICE',
    a: 'os',
    b: 'path',
    c: 'fs',
    d: 'http',
    answer: 'c',
    explanation: 'Module `fs` cung cấp các hàm để làm việc với hệ thống tệp trong Node.js.'
  },
  {
    content: 'Trong MongoDB, phương thức nào được dùng để chèn nhiều tài liệu vào một collection?',
    type: 'SINGLE_CHOICE',
    a: 'insert()',
    b: 'insertOne()',
    c: 'insertMany()',
    d: 'bulkInsert()',
    answer: 'c',
    explanation: '`insertMany()` được dùng để chèn nhiều tài liệu vào một collection.'
  },
  {
    content: 'Ngôn ngữ lập trình nào chủ yếu được dùng để phát triển ứng dụng Android?',
    type: 'SINGLE_CHOICE',
    a: 'Swift',
    b: 'Kotlin',
    c: 'C#',
    d: 'Ruby',
    answer: 'b',
    explanation: 'Kotlin là ngôn ngữ chính thức để phát triển ứng dụng Android.'
  },
  {
    content: 'Hàm nào trong JavaScript trả về độ dài của một chuỗi?',
    type: 'SINGLE_CHOICE',
    a: 'length()',
    b: 'size()',
    c: 'length',
    d: 'count()',
    answer: 'c',
    explanation: 'Thuộc tính `length` của chuỗi trả về số ký tự trong chuỗi.'
  },
  {
    content: 'Ký hiệu nào được dùng để khai báo biến trong JavaScript?',
    type: 'SINGLE_CHOICE',
    a: 'var',
    b: 'let',
    c: 'const',
    d: 'Tất cả các đáp án trên',
    answer: 'd',
    explanation: 'Trong JavaScript, bạn có thể dùng `var`, `let` hoặc `const` để khai báo biến.'
  },
  {
    content: 'Trong hệ điều hành Linux, lệnh nào được dùng để liệt kê các tệp trong thư mục?',
    type: 'SINGLE_CHOICE',
    a: 'dir',
    b: 'list',
    c: 'ls',
    d: 'show',
    answer: 'c',
    explanation: 'Lệnh `ls` liệt kê tất cả các tệp và thư mục trong thư mục hiện tại.'
  },
  {
    content: 'Phương thức HTTP nào thường được sử dụng để gửi dữ liệu đến máy chủ?',
    type: 'SINGLE_CHOICE',
    a: 'GET',
    b: 'POST',
    c: 'PUT',
    d: 'DELETE',
    answer: 'b',
    explanation: 'Phương thức POST được dùng để gửi dữ liệu đến máy chủ.'
  },
  {
    content: 'Thành phần nào của máy tính thực hiện các phép toán và logic?',
    type: 'SINGLE_CHOICE',
    a: 'RAM',
    b: 'CPU',
    c: 'Hard Drive',
    d: 'Power Supply',
    answer: 'b',
    explanation: 'CPU (Central Processing Unit) là thành phần thực hiện các phép toán và logic.'
  },
  {
    content: 'Hàm nào trong PHP dùng để nối chuỗi?',
    type: 'SINGLE_CHOICE',
    a: 'concat()',
    b: 'join()',
    c: '. (dấu chấm)',
    d: 'append()',
    answer: 'c',
    explanation: 'Trong PHP, dấu `.` được dùng để nối chuỗi.'
  },
  {
    content: 'Hàm nào trong Python trả về số phần tử của một danh sách?',
    type: 'SINGLE_CHOICE',
    a: 'size()',
    b: 'count()',
    c: 'length()',
    d: 'len()',
    answer: 'd',
    explanation: 'Hàm `len()` trả về số phần tử trong danh sách.'
  },
  {
    content: 'Trong SQL, từ khóa nào dùng để lọc các bản ghi trùng lặp?',
    type: 'SINGLE_CHOICE',
    a: 'UNIQUE',
    b: 'DISTINCT',
    c: 'LIMIT',
    d: 'GROUP BY',
    answer: 'b',
    explanation: '`DISTINCT` được dùng để loại bỏ các bản ghi trùng lặp trong kết quả.'
  },
  {
    content: 'Thẻ nào trong HTML5 được dùng để phát video?',
    type: 'SINGLE_CHOICE',
    a: '<audio>',
    b: '<video>',
    c: '<media>',
    d: '<source>',
    answer: 'b',
    explanation: 'Thẻ `<video>` trong HTML5 được dùng để phát video.'
  },
  {
    content: 'Công cụ nào phổ biến để quản lý phiên bản mã nguồn?',
    type: 'SINGLE_CHOICE',
    a: 'Git',
    b: 'SVN',
    c: 'Mercurial',
    d: 'Tất cả các đáp án trên',
    answer: 'd',
    explanation: 'Git, SVN và Mercurial đều là các công cụ quản lý phiên bản mã nguồn.'
  }
]
const explanationData = questionExamples.map(item => item.explanation)
/**
 * Generate sample questions data.
 *
 * This function generates an array of sample questions data. Each question entry includes
 * an instruction, content, type, multiple options (a to p), and an answer.
 *
 * @author Canh
 * @returns {Promise<Array<Object>>} A promise that resolves to an array of question objects.
 */
const generateQuestions = async () => {
  const questions = []
  for (let i = 0; i < questionExamples.length; i++) {
    const content = questionExamples[i].content
    const explanation = explanationData[i]
    const type = questionExamples[i].type

    let answer
    if (type === 'MULTIPLE_CHOICE' || type === 'SINGLE_CHOICE') {
      answer = questionExamples[i].answer
    } else {
      answer = questionExamples[i].answer
    }

    const options = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p']
    const questionOptions = {}
    options.forEach(option => {
      questionOptions[option] = questionExamples[i][option] || ''
    })
    questions.push({
      instruction: instructionExamples[Math.floor(Math.random() * instructionExamples.length)],
      content,
      type,
      ...questionOptions,
      answer,
      explanation,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent()
    })
  }
  return questions
}
/**
 * Seed the questions table with sample data.
 *
 * This function seeds the questions table with sample data generated by the generateQuestions function.
 * It first checks if the table is empty, and if so, it populates the table with the generated data.
 *
 * @author Canh
 * @returns {Promise<void>} A promise that resolves when the seeding is complete.
 */
const seedQuestions = async () => {
  try {
    // Check if the questions table is empty
    const count = await Question.count()
    if (count === 0) {
      // If the table is empty, generate sample questions data
      const questions = await generateQuestions()
      // Bulk create the sample data
      await Question.bulkCreate(questions, { validate: true })
    } else {
      // If the table is not empty, log a message
      console.log('Question table is not empty.')
    }
  } catch (error) {
    // Log any errors that occur during the seeding process
    console.log(`Failed to seed Question data: ${error}`)
  }
}

module.exports = seedQuestions
