const { fakerEN: faker } = require('@faker-js/faker')
const QuestionDiscussion = require('../models/questionDiscussion')
const User = require('../models/user')
const Question = require('../models/question')
/**
 * Generate a random user ID.
 *
 * This function retrieves all users from the database, extracts their IDs,
 * and returns a randomly selected user ID.
 *
 * @author Canh
 * @returns {Promise<number>} A promise that resolves to a random user ID.
 */
const generateUserId = async () => {
  const users = await User.findAll()
  const userIds = users.map(user => user.id)
  const randomIndex = Math.floor(Math.random() * userIds.length)
  const randomUserId = userIds[randomIndex]
  return randomUserId
}
/**
 * Generate a random question ID.
 *
 * This function retrieves all questions from the database, extracts their IDs,
 * and returns a randomly selected question ID.
 *
 * @author Canh
 * @returns {Promise<number>} A promise that resolves to a random question ID.
 */
const generateQuestionId = async () => {
  const questions = await Question.findAll()
  const questionIds = questions.map(question => question.id)
  const randomIndex = Math.floor(Math.random() * questionIds.length)
  const randomQuestionId = questionIds[randomIndex]
  return randomQuestionId
}

const discussionCommentExamples = [
  'The difficulty level of this question is too high for beginners.',
  'There seems to be a mistake in the explanation provided for option B.',
  'Can we add more context to the discussion thread for better understanding?',
  'The discussion thread for this question needs moderation due to inappropriate comments.',
  'It would be helpful to provide references supporting the explanation.',
  'Is there any alternative approach to solving this question?',
  "Let's brainstorm ideas to improve the clarity of the question stem.",
  'I suggest adding more distractors to make the multiple-choice options more challenging.',
  'The discussion on this question has diverged from the main topic. Can we refocus?',
  'There is a debate regarding the correctness of option C. We need clarification from subject matter experts.'
]
/**
 * Generate sample question discussion data.
 *
 * This function generates an array of sample question discussion data, ensuring that
 * each user-question pair is unique. Each question discussion entry includes user ID,
 * question ID, comment, creation date, and update date.
 *
 * @author Canh
 * @returns {Promise<Array<Object>>} A promise that resolves to an array of question discussion objects.
 */
const generateQuestionDiscussion = async () => {
  const usedPairs = new Set()
  const questionDiscussions = []
  let count = 0
  while (questionDiscussions.length < 10) {
    const userId = await generateUserId()
    const questionId = await generateQuestionId()
    const pair = `${userId}-${questionId}`
    if (!usedPairs.has(pair)) {
      const comment = discussionCommentExamples[count]
      usedPairs.add(pair)
      questionDiscussions.push({
        userId,
        questionId,
        comment,
        createdAt: faker.date.past(),
        updatedAt: faker.date.recent()
      })
    }
    count = count + 1
  }
  return questionDiscussions
}
/**
 * Seed the question discussions table with sample data.
 *
 * This function seeds the question discussions table with sample data generated by the generateQuestionDiscussion function.
 * It first checks if the table is empty, and if so, it populates the table with the generated data.
 *
 * @author Canh
 * @returns {Promise<void>} A promise that resolves when the seeding is complete.
 */
const seedQuestionDiscussions = async () => {
  try {
    // Check if the question discussions table is empty
    const count = await QuestionDiscussion.count()
    if (count === 0) {
      // If the table is empty, generate sample question discussions data
      const questionDiscussions = await generateQuestionDiscussion()
      // Bulk create the sample data
      await QuestionDiscussion.bulkCreate(questionDiscussions, { validate: true })
    } else {
      // If the table is not empty, log a message
      console.log('QuestionDiscussion table is not empty.')
    }
  } catch (error) {
    // Log any errors that occur during the seeding process
    console.log(`Failed to seed QuestionDiscussion data: ${error}`)
  }
}

module.exports = seedQuestionDiscussions
