const { fakerEN: faker } = require('@faker-js/faker')
const RoleToPermission = require('../models/role_to_permission')
const Role = require('../models/role')
const Permission = require('../models/permission')
/**
 * Generate a random role ID.
 *
 * This function retrieves all roles from the database, extracts their IDs,
 * and returns a randomly selected role ID.
 *
 * @author Canh
 * @returns {Promise<number>} A promise that resolves to a random role ID.
 */
const generateRoleId = async () => {
  const roles = await Role.findAll()
  const roleIds = roles.map(role => role.id)
  const randomIndex = Math.floor(Math.random() * roleIds.length)
  const randomRoleId = roleIds[randomIndex]
  return randomRoleId
}
/**
 * Generate a random permission ID.
 *
 * This function retrieves all permissions from the database, extracts their IDs,
 * and returns a randomly selected permission ID.
 *
 * @author Canh
 * @returns {Promise<number>} A promise that resolves to a random permission ID.
 */
const generatePermissionId = async () => {
  const permissions = await Permission.findAll()
  const permissionIds = permissions.map(permission => permission.id)
  const randomIndex = Math.floor(Math.random() * permissionIds.length)
  const randomPermissionId = permissionIds[randomIndex]
  return randomPermissionId
}
/**
 * Generate sample role-to-permission data.
 *
 * This function generates an array of sample role-to-permission data, ensuring that
 * each role-permission pair is unique. Each role-to-permission entry includes role ID,
 * permission ID, creation date, and update date. If the role ID is 1, it assigns permissions 1, 2, and 3.
 *
 * @author Canh
 * @returns {Promise<Array<Object>>} A promise that resolves to an array of role-to-permission objects.
 */
const generateRoleToPermission = async () => {
  const usedPairs = new Set()
  const roleToPermissions = []

  while (roleToPermissions.length < 6) {
    const roleId = await generateRoleId()
    let permissionIds = []

    if (roleId === 1) {
      permissionIds = [1, 2, 3]
    } else {
      const permissionId = await generatePermissionId()
      permissionIds.push(permissionId)
    }

    for (const permissionId of permissionIds) {
      const pair = `${roleId}-${permissionId}`

      if (!usedPairs.has(pair)) {
        usedPairs.add(pair)
        roleToPermissions.push({
          roleId,
          permissionId,
          createdAt: faker.date.past(),
          updatedAt: faker.date.recent()
        })
      }
    }
  }
  return roleToPermissions
}

/**
 * Seed the role-to-permission table with sample data.
 *
 * This function seeds the role-to-permission table with sample data generated by the generateRoleToPermission function.
 * It first checks if the table is empty, and if so, it populates the table with the generated data.
 *
 * @author Canh
 * @returns {Promise<void>} A promise that resolves when the seeding is complete.
 */
const seedRoleToPermissions = async () => {
  try {
    // Check if the role-to-permission table is empty
    const count = await RoleToPermission.count()
    if (count === 0) {
      // If the table is empty, generate sample role-to-permission data
      const roleToPermissions = await generateRoleToPermission()
      // Bulk create the sample data
      await RoleToPermission.bulkCreate(roleToPermissions, { validate: true })
    } else {
      // If the table is not empty, log a messages
      console.log('RoleToPermission table is not empty.')
    }
  } catch (error) {
    // Log any errors that occur during the seeding process
    console.log(`Failed to seed RoleToPermission data: ${error}`)
  }
}

module.exports = seedRoleToPermissions
