/* eslint-disable no-unused-vars */
const { fakerEN: faker } = require('@faker-js/faker')
const Exam = require('../models/exam')
const Question = require('../models/question')
const TempUserAnswer = require('../models/tempUserAnswer')
const User = require('../models/user')

/**
 * Generate a random question ID.
 *
 * This function retrieves all questions from the database, extracts their IDs,
 * and returns a randomly selected question ID.
 *
 * @author Canh
 * @returns {Promise<number>} A promise that resolves to a random question ID.
 */
const generateQuestionId = async () => {
  const questions = await Question.findAll()
  const questionIds = questions.map(question => question.id)
  const randomIndex = Math.floor(Math.random() * questionIds.length)
  const randomQuestionId = questionIds[randomIndex]
  return randomQuestionId
}

/**
 * Generate a random exam ID.
 *
 * This function retrieves all exams from the database, extracts their IDs,
 * and returns a randomly selected exam ID.
 *
 * @author Canh
 * @returns {Promise<number>} A promise that resolves to a random exam ID.
 */
const generateExamId = async () => {
  const exams = await Exam.findAll()
  const examIds = exams.map(exam => exam.id)
  const randomIndex = Math.floor(Math.random() * examIds.length)
  const randomExamId = examIds[randomIndex]
  return randomExamId
}

/**
 * Generate a random user ID.
 *
 * This function retrieves all users from the database, extracts their IDs,
 * and returns a randomly selected user ID.
 *
 * @author Canh
 * @returns {Promise<number>} A promise that resolves to a random user ID.
 */
const generateUserId = async () => {
  const users = await User.findAll()
  const userIds = users.map(user => user.id)
  const randomIndex = Math.floor(Math.random() * userIds.length)
  const randomUserId = userIds[randomIndex]
  return randomUserId
}

const userAnswerExample = ['insufficient light source', 'cannot see the license plate', 'traffic light is red', 'traffic light is green', 'speeding', 'broken', 'slippery road', 'road is too crowded', 'street light is not bright', 'traffic light is yellow']
/**
 * Generate sample temporary user answer data.
 *
 * This function generates an array of sample temporary user answer data, ensuring that
 * each exam-question-user pair is unique. Each temporary user answer entry includes user ID,
 * exam ID, question ID, user answer, creation date, and update date.
 *
 * @author Canh
 * @returns {Promise<Array<Object>>} A promise that resolves to an array of temporary user answer objects.
 */
const generateTempUserAnswer = async () => {
  console.log('Generating temporary user answers...')
  // const usedPairs = new Set()
  // const temptUserAnswers = []
  // let count = 0
  // while (temptUserAnswers.length < 10) {
  //   const examId = await generateExamId()
  //   const questionId = await generateQuestionId()
  //   const userId = await generateUserId()
  //   const pair = `${examId}-${questionId}-${userId}`

  //   if (!usedPairs.has(pair)) {
  //     const userAnswer = userAnswerExample[count]
  //     usedPairs.add(pair)
  //     temptUserAnswers.push({
  //       userId,
  //       examId,
  //       questionId,
  //       userAnswer,
  //       createdAt: faker.date.past(),
  //       updatedAt: faker.date.recent()
  //     })
  //   }
  //   count = count + 1
  // }
  // return temptUserAnswers
}

/**
 * Seed the temporary user answers table with sample data.
 *
 * This function seeds the temporary user answers table with sample data generated by the generateTempUserAnswer function.
 * It first checks if the table is empty, and if so, it populates the table with the generated data.
 *
 * @author Canh
 * @returns {Promise<void>} A promise that resolves when the seeding is complete.
 */
const seedTempUserAnswer = async () => {
  try {
    // Check if the temporary user answers table is empty
    const count = await TempUserAnswer.count()
    if (count === 0) {
      // If the table is empty, generate sample temporary user answers data
      const tempUserAnswers = await generateTempUserAnswer()
      // Bulk create the sample data
      await TempUserAnswer.bulkCreate(tempUserAnswers, { validate: true })
    } else {
      // If the table is not empty, log a message
      console.log('TempUserAnswer table is not empty.')
    }
  } catch (error) {
    // Log any errors that occur during the seeding process
    console.log(`Failed to seed TempUserAnswer data: ${error}`)
  }
}

module.exports = seedTempUserAnswer
