const { fakerEN: faker } = require('@faker-js/faker')
const UserEnterExitExamRoom = require('../models/userEnterExitExamRoom')
const User = require('../models/user')
const Exam = require('../models/exam')
/**
 * Generate a random user ID.
 *
 * This function retrieves all users from the database, extracts their IDs,
 * and returns a randomly selected user ID.
 *
 * @author Canh
 * @returns {Promise<number>} A promise that resolves to a random user ID.
 */
const generateUserId = async () => {
  const users = await User.findAll()
  const userIds = users.map(user => user.id)
  const randomIndex = Math.floor(Math.random() * userIds.length)
  const randomUserId = userIds[randomIndex]
  return randomUserId
}
/**
 * Generate a random exam ID.
 *
 * This function retrieves all exams from the database, extracts their IDs,
 * and returns a randomly selected exam ID.
 *
 * @author Canh
 * @returns {Promise<number>} A promise that resolves to a random exam ID.
 */
const generateExamId = async () => {
  const exams = await Exam.findAll()
  const examIds = exams.map(exam => exam.id)
  const randomIndex = Math.floor(Math.random() * examIds.length)
  const randomExamId = examIds[randomIndex]
  return randomExamId
}
/**
 * Generate sample user enter/exit exam room data.
 *
 * This function generates an array of sample user enter/exit exam room data, ensuring that
 * each user-exam pair is unique. Each entry includes user ID, exam ID, enter time, exit time,
 * attempt count, creation date, and update date.
 *
 * @author Canh
 * @returns {Promise<Array<Object>>} A promise that resolves to an array of user enter/exit exam room objects.
 */
const generateUserEnterExitExamRooms = async () => {
  const usedPairs = new Set()
  const userEnterExitExamRooms = []

  while (userEnterExitExamRooms.length < 6) {
    const userId = await generateUserId()
    const examId = await generateExamId()
    const pair = `${userId}-${examId}`

    if (!usedPairs.has(pair)) {
      usedPairs.add(pair)
      userEnterExitExamRooms.push({
        userId,
        examId,
        enterTime: faker.date.past(),
        exitTime: faker.date.recent(),
        attempt: faker.number.int({ min: 1, max: 3 }),
        createdAt: faker.date.past(),
        updatedAt: faker.date.recent()
      })
    }
  }
  return userEnterExitExamRooms
}

/**
 * Seed the user enter/exit exam rooms table with sample data.
 *
 * This function seeds the user enter/exit exam rooms table with sample data generated by the generateUserEnterExitExamRooms function.
 * It first checks if the table is empty, and if so, it populates the table with the generated data.
 *
 * @author Canh
 * @returns {Promise<void>} A promise that resolves when the seeding is complete.
 */
const seedUserEnterExitExamRooms = async () => {
  try {
    // Check if the user enter/exit exam rooms table is empty
    const count = await UserEnterExitExamRoom.count()
    if (count === 0) {
      // If the table is empty, generate sample user enter/exit exam rooms data
      const userEnterExitExamRooms = await generateUserEnterExitExamRooms()
      // Bulk create the sample data
      await UserEnterExitExamRoom.bulkCreate(userEnterExitExamRooms, { validate: true })
    } else {
      // If the table is not empty, log a message
      console.log('UserEnterExitExamRoom table is not empty.')
    }
  } catch (error) {
    // Log any errors that occur during the seeding process
    console.log(`Failed to seed UserEnterExitExamRoom data: ${error}`)
  }
}

module.exports = seedUserEnterExitExamRooms
