const { fakerEN: faker } = require('@faker-js/faker')
const Exam = require('../models/exam')
const Question = require('../models/question')
const UserAnswerHistory = require('../models/userAnswerHistory')
const User = require('../models/user')
/**
 * Generate a random question ID.
 *
 * This function retrieves all questions from the database, extracts their IDs,
 * and returns a randomly selected question ID.
 *
 * @author Canh
 * @returns {Promise<number>} A promise that resolves to a random question ID.
 */
const generateQuestionId = async () => {
  const questions = await Question.findAll()
  const questionIds = questions.map(question => question.id)
  const randomIndex = Math.floor(Math.random() * questionIds.length)
  const randomQuestionId = questionIds[randomIndex]
  return randomQuestionId
}
/**
 * Generate a random exam ID.
 *
 * This function retrieves all exams from the database, extracts their IDs,
 * and returns a randomly selected exam ID.
 *
 * @author Canh
 * @returns {Promise<number>} A promise that resolves to a random exam ID.
 */
const generateExamId = async () => {
  const exams = await Exam.findAll()
  const examIds = exams.map(exam => exam.id)
  const randomIndex = Math.floor(Math.random() * examIds.length)
  const randomExamId = examIds[randomIndex]
  return randomExamId
}
/**
 * Generate a random user ID.
 *
 * This function retrieves all users from the database, extracts their IDs,
 * and returns a randomly selected user ID.
 *
 * @author Canh
 * @returns {Promise<number>} A promise that resolves to a random user ID.
 */
const generateUserId = async () => {
  const users = await User.findAll()
  const userIds = users.map(user => user.id)
  const randomIndex = Math.floor(Math.random() * userIds.length)
  const randomUserId = userIds[randomIndex]
  return randomUserId
}

const userAnswerExample = ['insufficient light source', 'cannot see the license plate', 'traffic light is red', 'traffic light is green', 'speeding', 'broken', 'slippery road', 'road is too crowded', 'street light is not bright', 'traffic light is yellow']
/**
 * Generate sample user answer history data.
 *
 * This function generates an array of sample user answer history data, ensuring that
 * each exam-question-user pair is unique. Each user answer history entry includes user ID,
 * exam ID, question ID, user answer, creation date, and update date.
 *
 * @author Canh
 * @returns {Promise<Array<Object>>} A promise that resolves to an array of user answer history objects.
 */
const generateUserAnswerHistory = async () => {
  const usedPairs = new Set()
  const userAnswerHistories = []
  let count = 0
  while (userAnswerHistories.length < 10) {
    const examId = await generateExamId()
    const questionId = await generateQuestionId()
    const userId = await generateUserId()
    const pair = `${examId}-${questionId}-${userId}`
    if (!usedPairs.has(pair)) {
      usedPairs.add(pair)
      const userAnswer = userAnswerExample[count]
      userAnswerHistories.push({
        attempt: faker.number.int({ min: 1, max: 3 }),
        userId,
        examId,
        questionId,
        userAnswer,
        score: faker.number.int({ min: 0, max: 100 }),
        isCorrect: faker.datatype.boolean(),
        overAllScore: faker.number.int({ min: 0, max: 100 }),
        createdAt: faker.date.past(),
        updatedAt: faker.date.recent()
      })
    }
    count = count + 1
  }
  return userAnswerHistories
}

/**
 * Seed the user answer histories table with sample data.
 *
 * This function seeds the user answer histories table with sample data generated by the generateUserAnswerHistory function.
 * It first checks if the table is empty, and if so, it populates the table with the generated data.
 *
 * @author Canh
 * @returns {Promise<void>} A promise that resolves when the seeding is complete.
 */
const seedUserAnswerHistories = async () => {
  try {
    // Check if the user answer histories table is empty
    const count = await UserAnswerHistory.count()
    if (count === 0) {
      // If the table is empty, generate sample user answer histories data
      const exams = await generateUserAnswerHistory()
      // Bulk create the sample data
      await UserAnswerHistory.bulkCreate(exams, { validate: true })
    } else {
      // If the table is not empty, log a message
      console.log('UserAnswerHistory table is not empty.')
    }
  } catch (error) {
    // Log any errors that occur during the seeding process
    console.log(`Failed to seed UserAnswerHistory data: ${error}`)
  }
}

module.exports = seedUserAnswerHistories
